import React from 'react';
import { ArrowLeft, Shield, Users, CreditCard, FileText, AlertCircle, Mail } from 'lucide-react';
import './index.scss';

const TermsConditions: React.FC = () => {
  const handleBackClick = () => {
    window.history.back();
  };

  return (
    <div className="terms-page">
      <div className="terms-page__container">
        {/* Title Section */}
        <div className="terms-page__title-section">
          <h1 className="terms-page__title">Terms & Conditions</h1>
          <p className="terms-page__subtitle">TradeLive24.com</p>
          <div className="terms-page__effective-date">
            <span>Last Updated: June 2026</span>
          </div>
        </div>

        {/* Content */}
        <div className="terms-page__content">
          {/* Overview Section */}
          <section className="terms-page__section">
            <div className="terms-page__section-header">
              <FileText className="terms-page__section-icon" size={24} />
              <h2>1. Overview</h2>
            </div>
            <div className="terms-page__section-content">
              {/* <p>
                Welcome to <strong>TradeLive24.com</strong>, a community-driven education hub operated by{' '}
                <strong>TradeLive Ventures LLC</strong>
              </p> */}
              <p>Welcome to <strong>TradeLive24.com</strong> (the "Platform"), a community-driven educational hub operated by LearnLive Ventures, a legal entity registered and established under the laws of Ras Al Khaimah (RAK), United Arab Emirates.
</p>
              {/* <p>By accessing our platform, you agree to these Terms & Conditions.</p>
              <p>
                TradeLive24 operates as a <strong>not-for-profit platform</strong> — all revenue is reinvested into hosting,
                maintenance, development, and supporting creators who contribute educational content.
              </p> */}
              <p>By accessing, browsing, or using this Platform, you acknowledge that you have read, understood, and agreed to be bound by these <strong>Terms & Conditions</strong>. <strong>TradeLive24</strong> operates strictly as a <strong>not-for-profit</strong> arm of LearnLive Ventures. All revenues generated by the Platform are directly reinvested into site hosting, maintenance, technological development, and supporting the independent creators who contribute educational content.</p>

            </div>
          </section>

          {/* Eligibility Section */}
          <section className="terms-page__section">
            <div className="terms-page__section-header">
              <Users className="terms-page__section-icon" size={24} />
              <h2>2. Eligibility</h2>
            </div>
            <div className="terms-page__section-content">
              {/* <p>You must be <strong>at least 18 years old</strong> to use this site.</p>
              <p>By registering, you confirm that you meet the age requirement.</p> */}

              <p>By registering an account or utilizing the Platform, you expressly represent and warrant that you are at least <strong>eighteen (18) years of age</strong> and possess the legal capacity to enter into this binding agreement. If you do not meet this age requirement, you must cease using the Platform immediately.</p>

            </div>
          </section>

          {/* Membership Section */}
          <section className="terms-page__section">
            <div className="terms-page__section-header">
              <Shield className="terms-page__section-icon" size={24} />
              <h2>3. Membership & Subscription Model</h2>
            </div>
            <div className="terms-page__section-content">
              {/* <p>TradeLive24 offers two user tiers:</p> */}
              <div className="terms-page__membership-tiers">
                <div className="terms-page__tier">
                  <div className="terms-page__tier-header">
                    {/* <div className="terms-page__tier-badge terms-page__tier-badge--free">Free</div> */}
                    <h3>TradeLive24 operates under a single, unified subscription tier to ensure streamlined access to our educational ecosystem:</h3>
                  </div>
                  <p>Premium Annual Membership: Access to all advanced educational modules, mentor-led content, community discussions, and premium analytical tools.</p>

                </div>
                <div className="terms-page__tier">
                  <div className="terms-page__tier-header">
                    {/* <div className="terms-page__tier-badge terms-page__tier-badge--paid">Paid</div> */}
                    <h3>Pricing: </h3>
                  </div>
                  <p>The membership is billed as a single annual subscription calculated at a rate of $5.00 USD per month.</p>
                </div>
                
              </div>
              <div className="terms-page__membership-note">
                <p>
                  {/* Membership fees are minimal and exist <strong>solely to sustain the platform</strong>, not for company profit. */}
                  All membership fees exist <strong>solely to sustain, secure, and scale the operational capabilities of the Platform</strong>, maintaining our mandate as a non-profit initiative.
                </p>
              </div>
            </div>
          </section>

          {/* Payment Policy Section */}
          <section className="terms-page__section">
            <div className="terms-page__section-header">
              <CreditCard className="terms-page__section-icon" size={24} />
              <h2>4. Payment & Renewal Policy</h2>
            </div>
            <div className="terms-page__section-content">
              <ul className="terms-page__policy-list">
                <li>
                  Payment Processing: All transactions are securely processed via authorized third-party gateways, including <strong>Stripe</strong> and <strong>CoinPayments</strong>.
                </li>
                <li>
                  {/* There is <strong>no refund policy</strong>, as payments directly support operational continuity. */}
                  <strong>No-Refund Policy:</strong> Due to the immediate allocation of capital toward operational continuity and server maintenance, all sales are final, and no refunds shall be issued
                </li>
                <li>
                  {/* Auto-renewals may occur annually unless cancelled before renewal. */}
                  <strong>Automatic Renewal:</strong> Subscriptions are set to automatically renew annually. It is the user's sole responsibility to cancel the subscription within their account portal prior to the renewal date to avoid future charges.

                </li>
              </ul>
            </div>
          </section>



          {/* 5. Educational & Financial Disclaimer */}

<section className="terms-page__section">
  <div className="terms-page__section-header">
    <AlertCircle className="terms-page__section-icon" size={24} />
    <h2>5. Educational & Financial Disclaimer</h2>
  </div>
  <div className="terms-page__section-content">
    <p>
      TradeLive24 is strictly an educational platform. The Platform does not provide
      financial, investment, tax, or legal advice. All materials, data, commentary,
      and tools are for informational and educational purposes only.
    </p>
    <p>
      Users assume absolute responsibility for their independent trading decisions,
      financial strategy, and any resulting profits or losses. By utilizing this
      Platform, you acknowledge that trading financial instruments involves substantial
      risk. TradeLive Ventures, LearnLive Ventures, its team, and its contributors
      assume no liability whatsoever for any financial outcomes or damages incurred.
    </p>
  </div>
</section>

{/* 6. Mentor Program */}

<section className="terms-page__section">
  <div className="terms-page__section-header">
    <Users className="terms-page__section-icon" size={24} />
    <h2>6. Mentor Program</h2>
  </div>
  <div className="terms-page__section-content">
    <p>
      Users may apply to become independent educators by submitting credentials to{" "}
      <a
        href="mailto:mentor@tradelive24.com"
        className="terms-page__contact-link"
      >
        mentor@tradelive24.com
      </a>.
      Mentors operate as independent contractors and creators; they are not
      employees, agents, or authorized financial representatives of LearnLive Ventures.
      The views expressed by mentors are entirely their own.
    </p>
  </div>
</section>

{/* 7. Community Conduct & Platform Integrity */}

<section className="terms-page__section">
  <div className="terms-page__section-header">
    <Shield className="terms-page__section-icon" size={24} />
    <h2>7. Community Conduct & Platform Integrity</h2>
  </div>
  <div className="terms-page__section-content">
    <p>
      To maintain a professional educational environment, all users must adhere to
      strict code-of-conduct guidelines. Users are explicitly prohibited from:
    </p>
    <ul className="terms-page__policy-list">
      <li>Engaging in abusive, defamatory, harassing, or unprofessional behavior.</li>
      <li>Posting misleading financial data, unsolicited promotional material, spam, or affiliate links.</li>
      <li>Impersonating other users, mentors, staff, or brand representatives.</li>
    </ul>
    <p>
      LearnLive Ventures reserves the absolute right to review, suspend, or
      permanently terminate accounts found in violation of these standards
      without prior notice or refund.
    </p>
  </div>
</section>

{/* 8. Intellectual Property Rights */}

<section className="terms-page__section">
  <div className="terms-page__section-header">
    <FileText className="terms-page__section-icon" size={24} />
    <h2>8. Intellectual Property Rights</h2>
  </div>
  <div className="terms-page__section-content">
    <p>
      All proprietary content, including but not limited to educational videos,
      text, graphics, site architecture, code, branding, and logos displayed on
      TradeLive24.com, is the exclusive intellectual property of LearnLive Ventures.
      Unauthorized copying, distribution, reproduction, broadcasting, or commercial
      resale of these materials is strictly prohibited and subject to legal recourse.
    </p>
  </div>
</section>

{/* 9. Non-Profit Allocation & Transparency */}

<section className="terms-page__section">
  <div className="terms-page__section-header">
    <Shield className="terms-page__section-icon" size={24} />
    <h2>9. Non-Profit Allocation & Transparency</h2>
  </div>
  <div className="terms-page__section-content">
    <p>
      In alignment with our structural mandate, LearnLive Ventures guarantees that
      100% of the platform revenue is allocated towards:
    </p>
    <ul className="terms-page__policy-list">
      <li>Global server hosting, security protocols, and infrastructure maintenance.</li>
      <li>Software development and user-experience upgrades.</li>
      <li>Compensating and supporting independent educational creators.</li>
    </ul>
    <p>
      The Platform explicitly prohibits commission structures, affiliate payouts,
      or multi-level referral incentives. Users may utilize their portal solely
      to purchase and gift membership activation codes to third parties.
    </p>
  </div>
</section>

{/* 10. Limitation of Liability & Damages Cap */}

<section className="terms-page__section">
  <div className="terms-page__section-header">
    <AlertCircle className="terms-page__section-icon" size={24} />
    <h2>10. Limitation of Liability & Damages Cap</h2>
  </div>
  <div className="terms-page__section-content">
    <p>
      To the maximum extent permitted by applicable law, in no event shall
      LearnLive Ventures, its parent entity, subsidiaries, officers, directors,
      employees, or independent mentors be liable for any indirect, incidental,
      special, consequential, or punitive damages, including but not limited to
      loss of profits, data, trading capital, or goodwill.
    </p>
    <p>
      <strong>Maximum Liability Cap:</strong> The total aggregate liability of
      LearnLive Ventures for any claim, judgment, or dispute arising out of or
      in connection with these Terms & Conditions, or the use of the Platform,
      shall under no circumstances exceed the total amount of subscription fees
      actually paid by the user to TradeLive24 during the twelve (12) months
      immediately preceding the event giving rise to the liability.
    </p>
  </div>
</section>

{/* 11. Governing Law, Jurisdiction, and Legal Fees */}

<section className="terms-page__section">
  <div className="terms-page__section-header">
    <Shield className="terms-page__section-icon" size={24} />
    <h2>11. Governing Law, Jurisdiction, and Legal Fees</h2>
  </div>
  <div className="terms-page__section-content">
    <p>
      <strong>Governing Law:</strong> These Terms & Conditions, and any dispute,
      controversy, or claim arising out of or relating to them, shall be governed
      by, construed, and enforced exclusively in accordance with the laws of the
      United Arab Emirates (UAE), as applicable in the Emirate of Ras Al Khaimah (RAK).
    </p>

<p>
  <strong>Exclusive Jurisdiction:</strong> Any legal action, suit, or proceeding
  arising out of this agreement shall be brought exclusively in the competent
  courts of the United Arab Emirates. You hereby explicitly waive any objection
  to the laying of venue in such courts and waive any claim that such courts
  represent an inconvenient forum.
</p>

<p>
  <strong>Allocation of Legal Fees & Costs:</strong> In the event that any user
  or third party initiates legal proceedings, arbitration, or formal complaints
  against LearnLive Ventures or the Platform, the initiating party shall bear
  100% of all legal expenses. This includes, but is not limited to, attorney
  fees, court filing fees, administrative costs, and expert witness expenses
  incurred by both parties, regardless of the ultimate outcome of the dispute.
</p>

  </div>
</section>

{/* 12. Termination of Service */}

<section className="terms-page__section">
  <div className="terms-page__section-header">
    <AlertCircle className="terms-page__section-icon" size={24} />
    <h2>12. Termination of Service</h2>
  </div>
  <div className="terms-page__section-content">
    <p>
      LearnLive Ventures reserves the right, at its sole discretion, to restrict,
      suspend, or terminate your access to all or any part of the Platform at any
      time, for any reason—including any breach of these Terms—without prior
      liability or obligation.
    </p>
  </div>
</section>


          {/* 13. Contact Information */}
          <section className="terms-page__section">
            <div className="terms-page__section-header">
              <Mail className="terms-page__section-icon" size={24} />
              <h2>13. Contact Information</h2>
            </div>
            <div className="terms-page__section-content">
              <p>
                <strong>General inquiries:</strong>{' '}
                <a href="mailto:support@tradelive24.com" className="terms-page__contact-link">support@tradelive24.com</a>
              </p>
              <p>
                <strong>Mentor applications:</strong>{' '}
                <a href="mailto:mentor@tradelive24.com" className="terms-page__contact-link">mentor@tradelive24.com</a>
              </p>
              <p>Corporate Entity: LearnLive Ventures, Ras Al Khaimah (RAK), United Arab Emirates</p>
            </div>
          </section>
        </div>

        {/* Footer (optional) */}
        {/* ...existing footer code (if any) ... */}
      </div>
    </div>
  );
};

export default TermsConditions;


//           5. Educational Disclaimer
//           <section className="terms-page__section">
//             <div className="terms-page__section-header">
//               <AlertCircle className="terms-page__section-icon" size={24} />
//               <h2>5. Educational Disclaimer</h2>
//             </div>
//             <div className="terms-page__section-content">
//               <p>
//                 TradeLive24 provides educational materials only. We do not offer financial or investment advice.
//                 Users are fully responsible for their trading decisions and any resulting profits or losses.
//                 By using our platform, you acknowledge that trading involves risk and agree that
//                 TradeLive24, its team, or contributors cannot be held liable for financial outcomes.
//               </p>
//             </div>
//           </section>

//           <section className="terms-page__section">
//             <div className="terms-page__section-header">
//               <Users className="terms-page__section-icon" size={24} />
//               <h2>6. Mentor Program</h2>
//             </div>
//             <div className="terms-page__section-content">
//               <p>
//                 Users may apply to become mentors by completing verification through{' '}
//                 <a href="mailto:mentor@tradelive24.com" className="terms-page__contact-link">mentor@tradelive24.com</a>.
//                 Mentors are independent educators, not employees or financial advisors of TradeLive Ventures LLC.
//               </p>
//             </div>
//           </section>

// \          <section className="terms-page__section">
//             <div className="terms-page__section-header">
//               <Shield className="terms-page__section-icon" size={24} />
//               <h2>7. Community Conduct</h2>
//             </div>
//             <div className="terms-page__section-content">
//               <ul className="terms-page__policy-list">
//                 <li>Maintain professionalism and respect in all discussions.</li>
//                 <li>Avoid posting misleading, abusive, or promotional content.</li>
//                 <li>Not impersonate any other user, mentor, or brand representative.</li>
//                 <li>Accounts violating these standards may be suspended or terminated.</li>
//               </ul>
//             </div>
//           </section>

//           <section className="terms-page__section">
//             <div className="terms-page__section-header">
//               <FileText className="terms-page__section-icon" size={24} />
//               <h2>8. Intellectual Property</h2>
//             </div>
//             <div className="terms-page__section-content">
//               <p>
//                 All educational materials, branding, videos, and site design are owned by TradeLive Ventures LLC.
//                 Users may not copy, distribute, or resell content without permission.
//               </p>
//             </div>
//           </section>

//           <section className="terms-page__section">
//             <div className="terms-page__section-header">
//               <Shield className="terms-page__section-icon" size={24} />
//               <h2>9. Non-Profit and Transparency Clause</h2>
//             </div>
//             <div className="terms-page__section-content">
//               <p>TradeLive24 does not operate for profit. All membership fees and income are used exclusively for:</p>
//               <ul className="terms-page__policy-list">
//                 <li>Site hosting and maintenance.</li>
//                 <li>Platform security and technology development.</li>
//                 <li>Supporting educational creators and improving content.</li>
//               </ul>
//               <p>
//                 There are no commissions, affiliate payouts, or referral incentives.
//                 Users may, however, gift memberships via activation codes purchased in their portal.
//               </p>
//             </div>
//           </section>

//           <section className="terms-page__section">
//             <div className="terms-page__section-header">
//               <AlertCircle className="terms-page__section-icon" size={24} />
//               <h2>10. Risk and Liability</h2>
//             </div>
//             <div className="terms-page__section-content">
//               <p>
//                 All users acknowledge that trading financial instruments carries inherent risk.
//                 TradeLive24 is not responsible for any trading losses or financial damages.
//                 Use of educational material is at your own discretion and risk.
//               </p>
//             </div>
//           </section>

//           <section className="terms-page__section">
//             <div className="terms-page__section-header">
//               <Shield className="terms-page__section-icon" size={24} />
//               <h2>11. Legal Proceedings</h2>
//             </div>
//             <div className="terms-page__section-content">
//               <p>
//                 This platform operates under Malaysian law, but TradeLive Ventures LLC does not entertain
//                 legal proceedings regarding trading outcomes or personal financial losses incurred by users.
//               </p>
//             </div>
//           </section>

//           <section className="terms-page__section">
//             <div className="terms-page__section-header">
//               <AlertCircle className="terms-page__section-icon" size={24} />
//               <h2>12. Termination of Service</h2>
//             </div>
//             <div className="terms-page__section-content">
//               <p>We reserve the right to suspend or terminate any account for violation of terms or misuse of the platform.</p>
//             </div>
//           </section>